// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW_6aaRBZWw3u_fpG1djK6LijseQ_aH-I',
    appId: '1:471366946421:web:863852eba5898f1cab723c',
    messagingSenderId: '471366946421',
    projectId: 'roll2win-385d2',
    authDomain: 'roll2win-385d2.firebaseapp.com',
    storageBucket: 'roll2win-385d2.firebasestorage.app',
    measurementId: 'G-HH57L3TSL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4nVn1F7JSyNDq8Iu-UMEUjmqHJ9-hts4',
    appId: '1:471366946421:android:d47ec8e34f98e04aab723c',
    messagingSenderId: '471366946421',
    projectId: 'roll2win-385d2',
    storageBucket: 'roll2win-385d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiSkuibrhAdHjArspnBEQKASAcGh4VPUg',
    appId: '1:471366946421:ios:88e3f4caacfe64d9ab723c',
    messagingSenderId: '471366946421',
    projectId: 'roll2win-385d2',
    storageBucket: 'roll2win-385d2.firebasestorage.app',
    iosBundleId: 'com.rolltwowin.in.roll2win',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiSkuibrhAdHjArspnBEQKASAcGh4VPUg',
    appId: '1:471366946421:ios:88e3f4caacfe64d9ab723c',
    messagingSenderId: '471366946421',
    projectId: 'roll2win-385d2',
    storageBucket: 'roll2win-385d2.firebasestorage.app',
    iosBundleId: 'com.rolltwowin.in.roll2win',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW_6aaRBZWw3u_fpG1djK6LijseQ_aH-I',
    appId: '1:471366946421:web:59a8310bd545d6afab723c',
    messagingSenderId: '471366946421',
    projectId: 'roll2win-385d2',
    authDomain: 'roll2win-385d2.firebaseapp.com',
    storageBucket: 'roll2win-385d2.firebasestorage.app',
    measurementId: 'G-9Y3V1CJ8Z1',
  );
}
